In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


import plotly.express as px

In [2]:
# Demo Dataset for the practice : 
data_set_name = sns.get_dataset_names()

In [3]:
print(data_set_name)

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']

In [4]:
df  =sns.load_dataset('tips')

In [5]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [6]:
!pip install "nbformat>=4.2.0"

Requirement already satisfied: nbformat>=4.2.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (5.10.4)
Requirement already satisfied: jsonschema>=2.6 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbformat>=4.2.0) (4.24.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbformat>=4.2.0) (2.21.1)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from nbformat>=4.2.0) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbformat>=4.2.0) (5.14.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0) (0.36.2)
Requirement already satisfied: attrs>=22.2.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0) (25.3.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0) (0.25.1)
Requirement already satisfied: platformdirs>=2.5 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat>=4.2.0) (4.3.8)
Requirement already satisfied: pywin32>=300 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat>=4.2.0) (310)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat>=4.2.0) (4.13.2)

[notice] A new release of pip is available: 23.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
!pip install notebook jupyterlab ipywidgets

Requirement already satisfied: notebook in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (7.4.3)
Requirement already satisfied: jupyterlab in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (4.4.3)
Requirement already satisfied: ipywidgets in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (8.1.7)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from notebook) (2.27.3)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from notebook) (2.16.0)
Requirement already satisfied: tornado>=6.2.0 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from notebook) (6.5.1)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from notebook) (0.2.4)
Requirement already satisfied: packaging in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (25.0)
Requirement already satisfied: httpx>=0.25.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (3.1.6)
Requirement already satisfied: jupyter-core in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyterlab) (5.8.1)
Requirement already satisfied: ipykernel>=6.5.0 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyterlab) (6.29.5)
Requirement already satisfied: setuptools>=41.1.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (65.5.0)
Requirement already satisfied: tomli>=1.2.2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (2.2.1)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (2.0.5)
Requirement already satisfied: traitlets in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (5.14.3)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (2.2.5)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets) (4.0.14)
Requirement already satisfied: comm>=0.1.3 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets) (0.2.2)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets) (3.0.15)
Requirement already satisfied: ipython>=6.1.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets) (8.36.0)
Requirement already satisfied: typing_extensions>=4.0.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from async-lru>=1.0.0->jupyterlab) (4.13.2)
Requirement already satisfied: certifi in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from httpx>=0.25.0->jupyterlab) (2025.4.26)
Requirement already satisfied: idna in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from httpx>=0.25.0->jupyterlab) (3.10)
Requirement already satisfied: httpcore==1.* in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from httpx>=0.25.0->jupyterlab) (1.0.9)
Requirement already satisfied: anyio in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from httpx>=0.25.0->jupyterlab) (4.9.0)
Requirement already satisfied: h11>=0.16 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab) (0.16.0)
Requirement already satisfied: pyzmq>=24 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from ipykernel>=6.5.0->jupyterlab) (26.4.0)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from ipykernel>=6.5.0->jupyterlab) (1.8.14)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from ipykernel>=6.5.0->jupyterlab) (8.6.3)
Requirement already satisfied: nest-asyncio in c:\users\vinay\appdata\roaming\python\python310\site-packages (from ipykernel>=6.5.0->jupyterlab) (1.6.0)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipykernel>=6.5.0->jupyterlab) (0.1.7)
Requirement already satisfied: psutil in c:\users\vinay\appdata\roaming\python\python310\site-packages (from ipykernel>=6.5.0->jupyterlab) (7.0.0)
Requirement already satisfied: pygments>=2.4.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.19.1)
Requirement already satisfied: colorama in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: stack_data in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: decorator in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: jedi>=0.16 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.51)
Requirement already satisfied: exceptiongroup in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jinja2>=3.0.3->jupyterlab) (3.0.2)
Requirement already satisfied: pywin32>=300 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyter-core->jupyterlab) (310)
Requirement already satisfied: platformdirs>=2.5 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyter-core->jupyterlab) (4.3.8)
Requirement already satisfied: overrides>=5.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (7.7.0)
Requirement already satisfied: nbconvert>=6.4.4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (7.16.6)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (0.22.1)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (0.12.0)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (2.0.15)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (0.5.3)
Requirement already satisfied: websocket-client>=1.7 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (1.8.0)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (1.8.3)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (25.1.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (0.18.1)
Requirement already satisfied: nbformat>=5.3.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (5.10.4)
Requirement already satisfied: babel>=2.10 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook) (2.17.0)
Requirement already satisfied: requests>=2.31 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook) (2.32.3)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook) (4.24.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook) (0.12.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from anyio->httpx>=0.25.0->jupyterlab) (1.3.1)
Requirement already satisfied: argon2-cffi-bindings in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook) (21.2.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)
Requirement already satisfied: referencing>=0.28.4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (0.36.2)
Requirement already satisfied: attrs>=22.2.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (2025.4.1)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (0.25.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client>=6.1.12->ipykernel>=6.5.0->jupyterlab) (2.9.0.post0)
Requirement already satisfied: rfc3339-validator in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (0.1.4)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (3.3.0)
Requirement already satisfied: pyyaml>=5.3 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (6.0.2)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (0.1.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (0.3.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (1.5.1)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (0.10.2)
Requirement already satisfied: defusedxml in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (0.7.1)
Requirement already satisfied: beautifulsoup4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (4.13.4)
Requirement already satisfied: bleach[css]!=5.0.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (6.2.0)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (3.1.3)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->notebook) (2.21.1)
Requirement already satisfied: wcwidth in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->notebook) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->notebook) (2.4.0)
Requirement already satisfied: pure-eval in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (0.2.3)
Requirement already satisfied: executing>=1.2.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (3.0.0)
Requirement already satisfied: webencodings in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (1.4.0)
Requirement already satisfied: jsonpointer>1.13 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (3.0.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (24.11.1)
Requirement already satisfied: isoduration in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (20.11.0)
Requirement already satisfied: fqdn in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (1.5.1)
Requirement already satisfied: uri-template in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (1.3.0)
Requirement already satisfied: six>=1.5 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->ipykernel>=6.5.0->jupyterlab) (1.17.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook) (1.17.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (2.7)
Requirement already satisfied: pycparser in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook) (2.22)
Requirement already satisfied: arrow>=0.15.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from isoduration->jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (1.3.0)
Requirement already satisfied: types-python-dateutil>=2.8.10 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from arrow>=0.15.0->isoduration->jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (2.9.0.20250516)

[notice] A new release of pip is available: 23.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
!pip install notebook
!pip install ipywidgets
!pip install jupyterlab
!pip install plotly --upgrade
!pip install nbformat --upgrade

Requirement already satisfied: notebook in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (7.4.3)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from notebook) (0.2.4)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from notebook) (2.16.0)
Requirement already satisfied: tornado>=6.2.0 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from notebook) (6.5.1)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from notebook) (2.27.3)
Requirement already satisfied: jupyterlab<4.5,>=4.4.3 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from notebook) (4.4.3)
Requirement already satisfied: anyio>=3.1.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (4.9.0)
Requirement already satisfied: jupyter-client>=7.4.4 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyter-server<3,>=2.4.0->notebook) (8.6.3)
Requirement already satisfied: overrides>=5.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (7.7.0)
Requirement already satisfied: traitlets>=5.6.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (5.14.3)
Requirement already satisfied: nbconvert>=6.4.4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (7.16.6)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyter-server<3,>=2.4.0->notebook) (5.8.1)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (1.8.3)
Requirement already satisfied: nbformat>=5.3.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (5.10.4)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (0.22.1)
Requirement already satisfied: pyzmq>=24 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyter-server<3,>=2.4.0->notebook) (26.4.0)
Requirement already satisfied: packaging>=22.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (25.0)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (3.1.6)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (2.0.15)
Requirement already satisfied: websocket-client>=1.7 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (1.8.0)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (0.5.3)
Requirement already satisfied: terminado>=0.8.3 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (0.18.1)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (25.1.0)
Requirement already satisfied: ipykernel>=6.5.0 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyterlab<4.5,>=4.4.3->notebook) (6.29.5)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<4.5,>=4.4.3->notebook) (2.0.5)
Requirement already satisfied: setuptools>=41.1.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<4.5,>=4.4.3->notebook) (65.5.0)
Requirement already satisfied: httpx>=0.25.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<4.5,>=4.4.3->notebook) (0.28.1)
Requirement already satisfied: tomli>=1.2.2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<4.5,>=4.4.3->notebook) (2.2.1)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<4.5,>=4.4.3->notebook) (2.2.5)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook) (4.24.0)
Requirement already satisfied: requests>=2.31 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook) (2.32.3)
Requirement already satisfied: babel>=2.10 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook) (2.17.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook) (0.12.0)
Requirement already satisfied: typing_extensions>=4.5 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook) (4.13.2)
Requirement already satisfied: idna>=2.8 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook) (3.10)
Requirement already satisfied: sniffio>=1.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook) (1.3.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook) (1.3.0)
Requirement already satisfied: argon2-cffi-bindings in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook) (21.2.0)
Requirement already satisfied: certifi in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from httpx>=0.25.0->jupyterlab<4.5,>=4.4.3->notebook) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from httpx>=0.25.0->jupyterlab<4.5,>=4.4.3->notebook) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab<4.5,>=4.4.3->notebook) (0.16.0)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (1.8.14)
Requirement already satisfied: nest-asyncio in c:\users\vinay\appdata\roaming\python\python310\site-packages (from ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (1.6.0)
Requirement already satisfied: psutil in c:\users\vinay\appdata\roaming\python\python310\site-packages (from ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (7.0.0)
Requirement already satisfied: ipython>=7.23.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (8.36.0)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (0.1.7)
Requirement already satisfied: comm>=0.1.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (0.2.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jinja2>=3.0.3->jupyter-server<3,>=2.4.0->notebook) (3.0.2)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (2025.4.1)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (0.25.1)
Requirement already satisfied: attrs>=22.2.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (25.3.0)
Requirement already satisfied: referencing>=0.28.4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (0.36.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client>=7.4.4->jupyter-server<3,>=2.4.0->notebook) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.4.0->notebook) (4.3.8)
Requirement already satisfied: pywin32>=300 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.4.0->notebook) (310)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (3.3.0)
Requirement already satisfied: rfc3339-validator in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (0.1.4)
Requirement already satisfied: pyyaml>=5.3 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (6.0.2)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (0.1.1)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (3.1.3)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (0.10.2)
Requirement already satisfied: defusedxml in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (0.7.1)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (1.5.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (0.3.0)
Requirement already satisfied: beautifulsoup4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (4.13.4)
Requirement already satisfied: bleach[css]!=5.0.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (6.2.0)
Requirement already satisfied: pygments>=2.4.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (2.19.1)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->notebook) (2.21.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->notebook) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->notebook) (2.4.0)
Requirement already satisfied: webencodings in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (1.4.0)
Requirement already satisfied: colorama in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (0.4.6)
Requirement already satisfied: decorator in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (5.2.1)
Requirement already satisfied: jedi>=0.16 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (0.19.2)
Requirement already satisfied: stack_data in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (0.6.3)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (3.0.51)
Requirement already satisfied: uri-template in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (24.11.1)
Requirement already satisfied: jsonpointer>1.13 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (3.0.0)
Requirement already satisfied: isoduration in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (20.11.0)
Requirement already satisfied: fqdn in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (1.5.1)
Requirement already satisfied: six>=1.5 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=7.4.4->jupyter-server<3,>=2.4.0->notebook) (1.17.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook) (1.17.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (2.7)
Requirement already satisfied: pycparser in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook) (2.22)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (0.8.4)
Requirement already satisfied: wcwidth in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (0.2.13)
Requirement already satisfied: arrow>=0.15.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from isoduration->jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (1.3.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (2.2.0)
Requirement already satisfied: pure-eval in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (0.2.3)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab<4.5,>=4.4.3->notebook) (3.0.0)
Requirement already satisfied: types-python-dateutil>=2.8.10 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from arrow>=0.15.0->isoduration->jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook) (2.9.0.20250516)

[notice] A new release of pip is available: 23.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: ipywidgets in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (8.1.7)
Requirement already satisfied: ipython>=6.1.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets) (8.36.0)
Requirement already satisfied: comm>=0.1.3 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets) (0.2.2)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets) (4.0.14)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets) (3.0.15)
Requirement already satisfied: colorama in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: decorator in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.51)
Requirement already satisfied: typing_extensions>=4.6 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (4.13.2)
Requirement already satisfied: pygments>=2.4.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.19.1)
Requirement already satisfied: stack_data in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: matplotlib-inline in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)
Requirement already satisfied: jedi>=0.16 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: exceptiongroup in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (1.3.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)
Requirement already satisfied: wcwidth in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (0.2.3)

[notice] A new release of pip is available: 23.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: jupyterlab in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (4.4.3)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (2.2.5)
Requirement already satisfied: traitlets in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (5.14.3)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (2.27.3)
Requirement already satisfied: setuptools>=41.1.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (65.5.0)
Requirement already satisfied: notebook-shim>=0.2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (0.2.4)
Requirement already satisfied: ipykernel>=6.5.0 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyterlab) (6.29.5)
Requirement already satisfied: jupyter-core in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyterlab) (5.8.1)
Requirement already satisfied: packaging in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (25.0)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (2.0.5)
Requirement already satisfied: tomli>=1.2.2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (2.2.1)
Requirement already satisfied: tornado>=6.2.0 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyterlab) (6.5.1)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (3.1.6)
Requirement already satisfied: httpx>=0.25.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (0.28.1)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab) (2.16.0)
Requirement already satisfied: typing_extensions>=4.0.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from async-lru>=1.0.0->jupyterlab) (4.13.2)
Requirement already satisfied: certifi in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from httpx>=0.25.0->jupyterlab) (2025.4.26)
Requirement already satisfied: anyio in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from httpx>=0.25.0->jupyterlab) (4.9.0)
Requirement already satisfied: httpcore==1.* in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from httpx>=0.25.0->jupyterlab) (1.0.9)
Requirement already satisfied: idna in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from httpx>=0.25.0->jupyterlab) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab) (0.16.0)
Requirement already satisfied: comm>=0.1.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipykernel>=6.5.0->jupyterlab) (0.2.2)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipykernel>=6.5.0->jupyterlab) (0.1.7)
Requirement already satisfied: pyzmq>=24 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from ipykernel>=6.5.0->jupyterlab) (26.4.0)
Requirement already satisfied: ipython>=7.23.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipykernel>=6.5.0->jupyterlab) (8.36.0)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from ipykernel>=6.5.0->jupyterlab) (8.6.3)
Requirement already satisfied: psutil in c:\users\vinay\appdata\roaming\python\python310\site-packages (from ipykernel>=6.5.0->jupyterlab) (7.0.0)
Requirement already satisfied: nest-asyncio in c:\users\vinay\appdata\roaming\python\python310\site-packages (from ipykernel>=6.5.0->jupyterlab) (1.6.0)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from ipykernel>=6.5.0->jupyterlab) (1.8.14)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jinja2>=3.0.3->jupyterlab) (3.0.2)
Requirement already satisfied: platformdirs>=2.5 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyter-core->jupyterlab) (4.3.8)
Requirement already satisfied: pywin32>=300 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyter-core->jupyterlab) (310)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (2.0.15)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (1.8.3)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (25.1.0)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.12.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.18.1)
Requirement already satisfied: nbconvert>=6.4.4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (7.16.6)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.5.3)
Requirement already satisfied: nbformat>=5.3.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (5.10.4)
Requirement already satisfied: websocket-client>=1.7 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (1.8.0)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.22.1)
Requirement already satisfied: overrides>=5.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (7.7.0)
Requirement already satisfied: requests>=2.31 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab) (2.32.3)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab) (4.24.0)
Requirement already satisfied: babel>=2.10 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab) (2.17.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab) (0.12.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from anyio->httpx>=0.25.0->jupyterlab) (1.3.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from anyio->httpx>=0.25.0->jupyterlab) (1.3.0)
Requirement already satisfied: argon2-cffi-bindings in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab) (21.2.0)
Requirement already satisfied: jedi>=0.16 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.19.2)
Requirement already satisfied: decorator in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (5.2.1)
Requirement already satisfied: pygments>=2.4.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (2.19.1)
Requirement already satisfied: stack_data in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.6.3)
Requirement already satisfied: colorama in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.4.6)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (3.0.51)
Requirement already satisfied: referencing>=0.28.4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (0.36.2)
Requirement already satisfied: attrs>=22.2.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (25.3.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (0.25.1)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (2025.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client>=6.1.12->ipykernel>=6.5.0->jupyterlab) (2.9.0.post0)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (3.3.0)
Requirement already satisfied: pyyaml>=5.3 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (6.0.2)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (0.1.1)
Requirement already satisfied: rfc3339-validator in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (0.1.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (1.5.1)
Requirement already satisfied: defusedxml in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.7.1)
Requirement already satisfied: beautifulsoup4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (4.13.4)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.10.2)
Requirement already satisfied: bleach[css]!=5.0.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (6.2.0)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (3.1.3)
Requirement already satisfied: jupyterlab-pygments in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.3.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab) (2.21.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab) (2.4.0)
Requirement already satisfied: webencodings in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (1.4.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.8.4)
Requirement already satisfied: webcolors>=24.6.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (24.11.1)
Requirement already satisfied: uri-template in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (1.3.0)
Requirement already satisfied: fqdn in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (1.5.1)
Requirement already satisfied: isoduration in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (3.0.0)
Requirement already satisfied: wcwidth in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.2.13)
Requirement already satisfied: six>=1.5 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->ipykernel>=6.5.0->jupyterlab) (1.17.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab) (1.17.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (2.7)
Requirement already satisfied: executing>=1.2.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.2.3)
Requirement already satisfied: pycparser in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab) (2.22)
Requirement already satisfied: arrow>=0.15.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from isoduration->jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (1.3.0)
Requirement already satisfied: types-python-dateutil>=2.8.10 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from arrow>=0.15.0->isoduration->jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (2.9.0.20250516)

[notice] A new release of pip is available: 23.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: plotly in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (6.1.2)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from plotly) (1.41.0)
Requirement already satisfied: packaging in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from plotly) (25.0)

[notice] A new release of pip is available: 23.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: nbformat in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (5.10.4)
Requirement already satisfied: jsonschema>=2.6 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbformat) (4.24.0)
Requirement already satisfied: traitlets>=5.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from nbformat) (5.8.1)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from nbformat) (2.21.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=2.6->nbformat) (0.36.2)
Requirement already satisfied: attrs>=22.2.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=2.6->nbformat) (25.3.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=2.6->nbformat) (0.25.1)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=2.6->nbformat) (2025.4.1)
Requirement already satisfied: pywin32>=300 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (310)
Requirement already satisfied: platformdirs>=2.5 in c:\users\vinay\appdata\roaming\python\python310\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.3.8)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\users\vinay\appdata\local\programs\python\python310\lib\site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.13.2)

[notice] A new release of pip is available: 23.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
# Now we can make the dataset with the different graphs : 
fig  = px.box(df , y="sex")
fig.show()

In [10]:
# Box Plots with other parameters :  

fig  = px.box(df , x="variable_name" , y = "another_variable_from_the_column") # This makes two box plots in the same graph
fig =  px.box(df , x="time" , y="total_bill" , points="all") # This makes a dispersion type of cloud in the graph to show along with the box plot. 
# The dispersion shows the minimum and the maximum for the graphs.  
# we also can write the outliers instead of points ( that is the default parameter )

fig  = px.box(df , x = "column_name" , y="Column_name_2" , color = "color_column" , points="all" , title="Title for the graph" , hover_data=["column_name"]) # Color should be for the categorical column

# For the box plots we also can use the nothched = True to make the ntoched box plot .




fig  = px.strip(df , x = "column_name" , y = "column_name")
fig.show() # THis makes only the data points visible and we can use this to show the dispersion of the data.

ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'] but received: variable_name

In [ ]:
### Histogram using plotly : 
fig  = px.histogram(df , x = "total_bill" , nbins=10)
fig.show()
fig  = px.histogram(data_frame_name  , x = "column_1" , histnorm  = "probability density") # Hisnorm shows the type of the graph we wanna see in the graph 
fig.update_layout(bargap = 0.2 )
fig.show()

# we can use the bargap for the bars to be near or far from the graph. 

# We canuse the hsitnorm=probability to get the histogram from the probability density.   we can also check the percent insted of probability density. 

# we can also make the histogram from the two variables :  

fig  = px.histogram(df , x = "" , color="")
fig.show()

# In here the x is the color and the numerical column is the x and the categorical column is the color. 
# we can also use the aggregate function insted of the default count :  

fig  = px.histogram(df , x="" , y="" , histfunc="avg")
fig.show()
# Insted of the average we also can use the other functions for the aggregate functions.

# For the patterns we can use the function as : 

fig  = px.histogram(df , x = "" , y="" , color="categorical variable" , pattern_shape="any categorical binary column")
fig.show()  # This makes the histogram visible with the cateogical part with the pattern in the histogram


# In histogram we also can add the text in the graph: 

fig  = px.histogram(df, x = "": , y="" , histfunc="" , nbins=10 , text_auto=True)
fig.show()

NameError: name 'data_frame_name' is not defined

In [ ]:
# Line Charts : 

df = px.data.gapminder()

df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [ ]:
fig = px.line(df , x = 'year' , y='lifeExp')
fig.show()

In [ ]:
# We can use the color. with the category as well. Make the color with the categoires to make it distinguish. margers=True

# To make the graph 2 or mroe scatter plots we can make the connected scatter plot.  Two or more variables poloted with the line connecting them pregferably year or etc related to time

# for this just first make the data frame with the required columns 2 or more and then the code for the scatter plot be same :

In [ ]:
# Scatter Plot using Plotly : 

df  = px.data.iris()
df.head()

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [ ]:
fig  = px.scatter(df , x='sepal_width' , y = 'sepal_length')
fig.show()

In [11]:
# TO add the legend and other parameters we can use the code as  /: 
df = px.scatter(df , x='sepal_length' , y='sepal_width')

ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'] but received: sepal_length

In [ ]:
# TO make the violin Plot we can make the Graph as : 

fig = px.violin(df , y = "column_name"  )
fig.show()

# FOr the two variables :: 


fig  = px.violin(df , y="Column_name" , box=True , points="all")
# The points can be outliers as well this only shows the oitliers. 

# we can show  the voilin with the graph using the voilin parameter. 

fig  = px.violin(df , y='column_name' , color="categorical_variable" , violinmode="overlay" ,hover_data=df.columns)
fig.update_traces(quartilemethod="exclusive") # This is used to make the traces we also can make the inclusive for the applicaiton : 
fig.show()